[tool.poetry]
name = "dsalgorithms-python"
version = "0.1.0"
description = ""
authors = ["T. E. Kalayci <tekrei@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
